#!/bin/sh -e
# $Id: bootstrap,v 1.1.1.1 2008/04/09 20:40:19 mark Exp $
# the list of commands that need to run before we do a compile

LIBTOOLIZE=no_libtoolize
case `uname` in
    Darwin)
	LIBTOOLIZE=glibtoolize ;;
    Linux)
	LIBTOOLIZE=libtoolize  ;;
esac

REQD_FILES="NEWS README ChangeLog"
for REQD_FILE in $REQD_FILES; do
    if test ! -f $REQD_FILE; then
	touch $REQD_FILE
    fi
done

aclocal
autoheader
$LIBTOOLIZE --copy --force
automake --add-missing --copy
autoconf

# next: ./configure --enable-maintainer-mode
